name: notes_app
description: "Desafio t√©cnico Notes App Flutter"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  go_router: ^14.2.0
  get_it: ^7.6.4
  mobx: ^2.3.0
  flutter_mobx: ^2.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  flutter_card_swiper: ^7.2.0
  flutter_staggered_grid_view: ^0.7.0
  uuid: ^4.5.2
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.0

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_logo_2.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFF5E6" 
  adaptive_icon_foreground: "assets/images/ic_logo_2.png"

flutter_native_splash:
  color: "#FFF5E6" 

  image: "assets/images/ic_logo.png"
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#FFF5E6"
    image: "assets/images/ic_logo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/images/